Automatically install Coder CLI (#9)
* Run preflight before all binary invocations

Otherwise the first command you run or action you perform will always
fail, then the binary will install, then you have to redo the action.

To accomplish this every command should call execCoder instead of
calling exec directly.

It did not appear necessary to have a separate exec and execCombined so
I removed exec and renamed execCombined to exec.

I also removed execJSON to avoid needing to have another function called
execCoderJSON since you can just wrap with JSON.parse which is pretty
minimal.

Lastly I refactored the install logic so it includes a progress bar and
can eventually support downloading the binary.

* Stream installation progress

Instead of waiting for the end.

We will be able to use this for logs as well.

* Make Coder CLI invocation an object

This seems safer than trying to split on spaces.

* Store extension context

This will be needed to get the path for storing the binary.

* Add code for making requests

* Add code for extracting tars and zips

* Download binary when not on PATH

diff --git a/fixtures/coder b/fixtures/coder
--- a/fixtures/coder
+++ b/fixtures/coder
@@ -7,6 +7,16 @@ need_login() {
   exit 1
 }
 
+fail() {
+  echo fail
+  exit 1
+}
+
+success () {
+  echo success
+  exit 0
+}
+
 workspaces() {
   cat ./workspaces.json
   exit 0
@@ -23,6 +33,8 @@ main() {
   # Mock the output based on the passed arguments.
   case "$*" in
     "envs ls --output json") workspaces ;;
+    "test fail") fail ;;
+    "test success") success ;;
     *) echo "$* is not mocked" ; exit 1 ;;
   esac
 }
